import {INodeGenerator} from "@/generators/inode-generator";

export function addGeneratedFileHeader(generator: INodeGenerator) {
    return `
    /*
    *   This file was auto generated and should be seen as read only
    *   Generated By: ${generator.name} | ${generator.version}
    */
    `;
}